---
title: "Lab 1"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Necessary Packages
```{r, message=FALSE}
library(mdsr)
```

# Loading in data
```{r}
walking <- read.csv("lab-1.csv", header = TRUE)
```

# Cleaning data
Getting rid of unnecessary
```{r}
walking <- walking %>% 
  select(-type, -desc, -name)
```

Making column names simpler
```{r}
walking <- walking %>% 
  rename(altitude = altitude..ft.) %>% 
  rename(speed = speed..mph.) %>% 
  rename(distance_mi = distance..mi.) %>% 
  rename(distance_int_ft = distance_interval..ft.)
```

# Summary stats
We will be working with a full population
```{r}
columns <- c(walking$time, walking$latitude, walking$longitude, walking$altitude, walking$speed, walking$distance_mi, walking$distance_int_ft)

sum_time <- favstats( ~ time, data = walking)
sum_time

sum_latitude <- favstats( ~ latitude, data = walking)
sum_latitude

sum_longitude <- favstats( ~ longitude, data = walking)
sum_longitude

sum_altitude <- favstats( ~ altitude, data = walking)
sum_altitude

sum_speed <- favstats( ~ speed, data = walking)
sum_speed

sum_distance_mi <- favstats( ~ distance_mi, data = walking)
sum_distance_mi

distance_int_ft <- as.numeric(walking$distance_int_ft)
sum_dist_int_ft <- favstats( ~ distance_int_ft, data = walking)
sum_dist_int_ft

```

Question 1:
The standard deviation



